theme: jekyll-theme-slate
title: Geometrik
description: A graphic library for Ogre-3D engine.
show_downloads: true

github:
  zip_url:
  owner_name: David de Lorenzo
  owner_url: https://sphinkie.github.io/